# Description: Docker compose file for Syslog-NG
# =============================================================================
services:
# =============================================================================
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    networks:
      - vbridge
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - syslog-ng-conf:/config
      - syslog-ng-log:/var/log
  # ---------------------------------------------------------------------------
volumes:
  syslog-ng-conf:
    name: syslog-ng-conf
  syslog-ng-log:
    name: syslog-ng-log
# =============================================================================
networks:
  vbridge:
    name: vbridge